version: "3.7"
services:
  app:
    build:
      args:
        user: plp
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: demo
    container_name: demo-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - demo
  db:
    image: mysql:8.0
    container_name: demo-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    ports:
      - 3306:3306
    networks:
      - demo
  nginx:
    image: nginx:1.17-alpine
    container_name: demo-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - demo
networks:
  demo:
    driver: bridge
volumes:
  dbdata:
    driver: local